apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ivson@part3s.com.br
    privateKeySecretRef:
      name: letsencrypt-tls # tls -> secretName -> ingress.yaml
    solvers:
    - http01:
        ingress:
          class: nginx