apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "ivsonv/hello-go:v6"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000   # port-container

            periodSeconds: 5
            failureThreshold: 3 #count ports to restart
            timeoutSeconds: 1
            successThreshold: 1

          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
          envFrom:
            - configMapRef:
                name: goserver-env